### PR TITLE
ch3 illustration

### PR DESCRIPTION
**Pull request by JhuTingLiang**

### CODE REVIEW

**Review by YiFang-Li — APPROVED** [review]
恐龍時代也要有毒蘋果啊

**Review by LiangTing-Yi — APPROVED** [review]
OK

**Review by kuochuanpan — APPROVED** [review]
確實

**Review by yoyochue — APPROVED** [review]
毒蘋果吃掉了??

**Review by GillWu — APPROVED** [review]
OK

**Pull request merged**
