### PR TITLE
chapter 1 v1.1

### PR DESCRIPTION
**Pull request by YiFang-Li**
merge chapter 1 v1.1 to main-comphys-112
we need 毒蘋果

### CODE REVIEW

**Review by YiFang-Li — COMMENTED** [review]
毒蘋果 is the best weapon

**Review by GillWu — APPROVED** [review]
你可以加毒蘋果

**Review by quantankevin — APPROVED** [review]

**Review by Noctis0522 — APPROVED** [review]

**Review by kuochuanpan — APPROVED** [review]
LGTM

**Review by LiangTing-Yi — APPROVED** [review]
LGTM

**Comment by JhuTingLiang** [comment]
XD

**Review by yoyochue — APPROVED** [review]
good

**Review by JhuTingLiang — APPROVED** [review]
XD

**Pull request merged**
